packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.8
  '@emotion/react': ^11.14.0
  '@emotion/styled': ^11.14.1
  '@fontsource/roboto': ^5.2.9
  '@mui/icons-material': ^7.3.6
  '@mui/material': ^7.3.6
  '@types/node': 24.10.2
  '@types/react-dom': ^19.2.3
  '@types/react': ^19.2.7
  '@vitejs/plugin-react-swc': ^4.2.2
  '@vitest/browser-playwright': ^4.0.15
  '@vitest/coverage-v8': ^4.0.15
  fast-xml-parser: ^5.3.3
  husky: ^9.1.7
  playwright: ^1.57.0
  react-dom: ^19.2.2
  react: ^19.2.2
  turbo: ^2.6.3
  typescript: ^5.9.3
  vite-plugin-devtools-json: ^1.0.0
  vite-tsconfig-paths: ^5.1.4
  vite: ^7.2.7
  vitest-browser-react: ^2.0.2
  vitest: ^4.0.15

minimumReleaseAge: 4320

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
