packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.8
  '@emotion/react': ^11.14.0
  '@emotion/styled': ^11.14.1
  '@fontsource/roboto': ^5.2.9
  '@mui/icons-material': ^7.3.6
  '@mui/material': ^7.3.6
  '@playwright/test': ^1.57.0
  '@types/node': 24.10.2
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react-swc': ^4.2.2
  '@vitest/browser-playwright': ^4.0.15
  '@vitest/coverage-v8': ^4.0.15
  fast-xml-parser: ^5.3.3
  husky: ^9.1.7
  i18next: ^25.7.2
  i18next-browser-languagedetector: ^8.2.0
  i18next-resources-to-backend: ^1.2.1
  playwright: ^1.57.0
  react: ^19.2.2
  react-dom: ^19.2.2
  react-i18next: ^16.5.0
  temml: 0.13.1
  turbo: ^2.6.3
  typescript: ^5.9.3
  vite: ^7.2.7
  vite-plugin-devtools-json: ^1.0.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.15
  vitest-browser-react: ^2.0.2

catalogMode: prefer

minimumReleaseAge: 4320

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
