packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.8
  '@types/node': ^24.10.2
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@vitejs/plugin-react-swc': ^4.2.2
  '@vitest/browser-playwright': ^4.0.15
  '@vitest/coverage-v8': ^4.0.15
  react: ^19.2.2
  react-dom: ^19.2.2
  playwright: ^1.57.0
  turbo: ^2.6.3
  typescript: ^5.9.3
  vite: ^7.2.7
  vite-plugin-devtools-json: ^1.0.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.15

minimumReleaseAge: 4320
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
